metadata:
  access_right: open
  license: CC-BY-4.0
  publication_type: article
  upload_type: publication
pipelines:
  co2-emissions:
    envs:
    - host
    path: pipelines/co2-emissions
    stages:
    - setup
    - run
    - validate
  docker-data-science:
    envs:
    - host
    path: pipelines/docker-data-science
    stages:
    - build-docker-image
    - generate-learning-curves
    - generate-figures
    - validate
  myexp:
    envs:
    - host
    path: pipelines/myexp
    stages:
    - setup
    - run
    - post-run
    - validate
    - teardown
popperized:
- github/popperized
